name: Build

on: 
  push:
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - run: make all
      - run: make all-arm

      - name: Retrieve version info
        id: version
        run: |
          can_commit="$(git -C can log -n 1 --pretty=format:"%H")"
          echo "::set-output name=can_commit::$can_commit"
          echo "::set-output name=date::$(date +"%Y.%m.%d_%H-%M")"

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.version.outputs.can_commit }}
          draft: false
          prerelease: false
          tag_name: ${{ steps.version.outputs.date }}-${{ steps.version.outputs.can_commit }}
          files: |
            build/eagle_candump_x86_64
            build/eagle_cansniffer_x86_64
            build/eagle_candump_arm
            build/eagle_cansniffer_arm

